# Generated by Django 5.0.6 on 2024-09-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_telegrambotcredentials_api_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotcredentials',
            name='user',
        ),
    ]
