# Generated by Django 5.0.6 on 2024-09-05 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_telegrambotcredentials_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telegrambotcredentials',
            old_name='bot_token',
            new_name='token',
        ),
    ]
