# Generated by Django 5.0.6 on 2024-09-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_delete_userlogindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotcredentials',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='csv_files/'),
        ),
        migrations.AddField(
            model_name='telegrambotcredentials',
            name='use_csv',
            field=models.BooleanField(default=False),
        ),
    ]
