# Generated by Django 5.0.6 on 2024-09-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apicredentials',
            options={'verbose_name': 'API Credentials', 'verbose_name_plural': 'API Credentials'},
        ),
        migrations.RemoveField(
            model_name='apicredentials',
            name='user',
        ),
        migrations.AlterField(
            model_name='apicredentials',
            name='api_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
