# Generated by Django 5.0.6 on 2024-09-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_alter_apicredentials_options_apicredentials_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredentials',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
