# Generated by Django 5.0.6 on 2024-09-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_apicredentials_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicredentials',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='apicredentials',
            name='user',
        ),
    ]
