# Generated by Django 5.0.6 on 2024-09-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_apicredentials_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotcredentials',
            name='csv_file',
        ),
        migrations.RemoveField(
            model_name='telegrambotcredentials',
            name='use_csv',
        ),
        migrations.AddField(
            model_name='telegrambotcredentials',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
