# Generated by Django 5.0.6 on 2024-09-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_rename_is_active_telegrambotcredentials_use_csv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicredentials',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
