# Generated by Django 5.0.6 on 2024-09-19 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_apicredentials_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrambotcredentials',
            name='csv_file',
        ),
        migrations.RemoveField(
            model_name='telegrambotcredentials',
            name='use_csv',
        ),
        migrations.AddField(
            model_name='telegrambotcredentials',
            name='phone_number',
            field=models.CharField(default='', max_length=13),
        ),
    ]
