# Generated by Django 4.2.16 on 2024-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_telegrambotstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambotcredentials',
            name='username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
