# Generated by Django 4.2.16 on 2024-09-23 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_telegrambotcredentials_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TelegramBotState',
        ),
    ]
