# Generated by Django 4.2.16 on 2024-09-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_minid_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='minid',
            name='destination_channel',
            field=models.CharField(default='', max_length=255),
        ),
    ]
